//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentList.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Student
    {
        public int Id { get; set; }

        [DisplayName("Full Name")]
        [Required(ErrorMessage = "Name is requred")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Gender is requred")]
        public string Gender { get; set; }

        [DisplayName("Date of Birth")]
        [Required(ErrorMessage = "Date of birth is requred")]
        [DataType(DataType.Date)]
        public string Dob { get; set; }

        [DisplayName("Mobile Number")]
        [Required(ErrorMessage = "Mobile Number of birth is requred")]
        [Range(01199999999, 01999999999, ErrorMessage = "Invalid mobile number.")]
        public Nullable<int> Mobile { get; set; }

        [DisplayName("Email Address")]
        [Required(ErrorMessage = "Email is requred")]
        [RegularExpression("^([0-9a-zA-Z]([-\\.\\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\\w]*[0-9a-zA-Z]\\.)+[a-zA-Z]{2,9})$", ErrorMessage = "Invail email")]
        public string Email { get; set; }


        public string Image { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
